# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-17 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('beans', models.IntegerField()),
                ('vip', models.BinaryField()),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('head_image', models.ImageField(blank=True, max_length=255, null=True, upload_to=b'images')),
                ('comp', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('edu', models.CharField(max_length=50)),
                ('mycomp', models.CharField(max_length=50)),
                ('myjob', models.CharField(max_length=50)),
                ('myintr', models.CharField(max_length=255)),
                ('mylocal', models.CharField(max_length=50)),
                ('mymoney', models.CharField(max_length=255)),
            ],
        ),
    ]
