# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-22 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_auto_20180117_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='myresume',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
