# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-23 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_user_myresume'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='graduate',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
