# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-23 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20180125_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appli_receiver', to='online.User'),
        ),
        migrations.AlterField(
            model_name='application',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appli_sender', to='online.User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online.User'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_receiver', to='online.User'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to='online.User'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to='online.User'),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online.User'),
        ),
    ]
